name: Code Quality & Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Linter
        run: npm run lint

      # Descomentar esta línea cuando tengamos pruebas configuradas en package.json
      # - name: Ejecutar Tests
      #   run: npm test